# Generated by Django 5.1.3 on 2024-12-20 05:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('blog_images', models.ImageField(upload_to='book_media')),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='book_media')),
                ('contact', models.IntegerField()),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=200)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.blog')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.registration')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.registration'),
        ),
    ]
